name: Refresh submodules

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{github.event}}
        echo ${{github.event_type}}
        echo ${{github.event.action}}
        echo ${{github.event.repository.ref}}
        echo ${{github.event.ref}}
        echo ${{github.event.repository}}
        echo ${{github.event.repository.full_name}}
        echo ${{github.event.repository.url}}
        echo done!!!
